version: '3.7'
services:
  server:
    image: rancher/k3s:v1.33.1-k3s1-amd64
    container_name: k3s-server
    networks:
    - default
    command: server --disable metrics-server --tls-san k3s-server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - ./k3s_data/kubeconfig:/output
    - ./k3s_data/docker_images:/var/lib/rancher/k3s/agent/images
    ports:
    - 80:80
    - 443:443
    - 6443:6443

  k3s-setup:
    image: dtzar/helm-kubectl:main
    depends_on:
      - server
    volumes:
      - ./k3s_data/kubeconfig:/kubeconfig:ro
      - ./k3s_data:/shared
    environment:
      - KUBECONFIG=/tmp/kubeconfig.yaml
    entrypoint: /bin/sh
    command: 
      - -c
      - |
        set -e
        sleep 60 # Wait for server to be ready

        echo 'Creating container kubeconfig...'
        # Create container-specific kubeconfig without modifying original
        cp /kubeconfig/kubeconfig.yaml /tmp/kubeconfig.yaml
        sed -i 's/127.0.0.1:6443/k3s-server:6443/g' /tmp/kubeconfig.yaml
        export KUBECONFIG=/tmp/kubeconfig.yaml
        
        echo 'Modified kubeconfig:'
        cat /tmp/kubeconfig.yaml | grep server:
        
        # Wait for cluster
        echo 'Waiting for cluster to be ready...'
        until kubectl get nodes 2>/dev/null; do 
          echo 'Still waiting for cluster...'
          sleep 5
        done
        
        echo 'K3s cluster is ready!'
        kubectl get nodes
        
        # Install Helm repos
        echo 'Adding Helm repositories...'
        helm repo add vulnerable-apps https://neuralegion.github.io/helmcharts/
        helm repo update
        
        # Create self-signed certificate
        echo 'Creating self-signed certificate...'
        apk add --no-cache openssl
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /tmp/tls.key -out /tmp/tls.crt \
          -subj '/CN=brokencrystals.local' \
          -addext 'subjectAltName=DNS:brokencrystals.local,DNS:auth.brokencrystals.local,DNS:mailcatcher.brokencrystals.local'
        
        kubectl create secret tls brokencrystals-tls \
          --cert=/tmp/tls.crt --key=/tmp/tls.key
              
        # Install brokencrystals first
        echo 'Installing brokencrystals application...'
        helm install brokencrystals vulnerable-apps/brokencrystals \
        --set ingress.url=brokencrystals.local \
        --set useMailcatcher=true \
        --wait --timeout=600s
        
        # NOW patch the ingresses to use Traefik
        echo 'Patching ingresses to use Traefik...'
        
        # Patch ingress classes
        kubectl patch ingress brokencrystals -p '{"spec":{"ingressClassName":"traefik"}}'
        kubectl patch ingress brokencrystals-keycloak -p '{"spec":{"ingressClassName":"traefik"}}'
        kubectl patch ingress brokencrystals-mailcatcher -p '{"spec":{"ingressClassName":"traefik"}}'
        
        # Remove nginx annotations and add traefik annotation
        echo 'Updating annotations for Traefik...'
        
        # Main ingress
        kubectl annotate ingress brokencrystals nginx.ingress.kubernetes.io/ssl-redirect- || true
        kubectl annotate ingress brokencrystals nginx.ingress.kubernetes.io/proxy-ssl-protocols- || true
        kubectl annotate ingress brokencrystals cert-manager.io/cluster-issuer- || true
        kubectl annotate ingress brokencrystals kubernetes.io/ingress.class=traefik
        
        # Keycloak ingress  
        kubectl annotate ingress brokencrystals-keycloak nginx.ingress.kubernetes.io/ssl-redirect- || true
        kubectl annotate ingress brokencrystals-keycloak nginx.ingress.kubernetes.io/proxy-ssl-protocols- || true
        kubectl annotate ingress brokencrystals-keycloak cert-manager.io/cluster-issuer- || true
        kubectl annotate ingress brokencrystals-keycloak kubernetes.io/ingress.class=traefik
        
        # Mailcatcher ingress
        kubectl annotate ingress brokencrystals-mailcatcher nginx.ingress.kubernetes.io/ssl-redirect- || true
        kubectl annotate ingress brokencrystals-mailcatcher nginx.ingress.kubernetes.io/proxy-ssl-protocols- || true
        kubectl annotate ingress brokencrystals-mailcatcher cert-manager.io/cluster-issuer- || true
        kubectl annotate ingress brokencrystals-mailcatcher kubernetes.io/ingress.class=traefik
        
        # Verify the changes
        echo '🔍 Verifying ingress configuration...'
        kubectl get ingress -o wide
        kubectl describe ingress brokencrystals | grep -E "(Class|Annotations)"
        
        # Check Traefik status
        echo 'Checking Traefik status...'
        kubectl get pods -n kube-system | grep traefik    

        echo '✅ Setup completed successfully!'
        echo 'Add these entries to your /etc/hosts:'
        echo '127.0.0.1 brokencrystals.local'
        echo '127.0.0.1 auth.brokencrystals.local'
        echo '127.0.0.1 mailcatcher.brokencrystals.local'
        
        # Keep container running
        tail -f /dev/null
      
    restart: "no"
volumes:
  k3s-server: {}
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.98.0.0/16" # Self-defined subnet on local machine
